### ISSUE TITLE
A typo?

### ISSUE THREAD

**Issue by ipadjen** [tudelft3d/3dbook#2]
Handout 2.2, subsection 1.3.1, page 5.

"This makes the method more flexible compared to a purely data driven approach that fits a pre-defined roof shape"

Shouldn't it be a model-driven approach that fits a pre-defined roof shape?

**Comment by Ylannl** [comment]
You are right, it should be model-driven.

**Comment by Ylannl** [comment]
fixed with db84b30a38b86ba904af1be877f1e9804003562a
